import { describe, expect, it } from "vitest";

import { generateNodeDockerfile, installCommand } from "../../src/services/detection/generateDockerfile.js";
import type { NodeProject } from "../../src/services/detection/nodeProject.js";

function project(overrides: Partial<NodeProject> = {}): NodeProject {
  return {
    packageManager: "npm",
    packageManagerMajor: null,
    packageManagerVersion: null,
    packageManagerReason: "package-lock.json → npm",
    staleLockfile: null,
    lockfile: "package-lock.json",
    nodeMajor: 24,
    hasBuildScript: true,
    startCommand: ["npm", "start"],
    dependencyFiles: null,
    notes: [],
    ...overrides,
  };
}

describe("generateNodeDockerfile", () => {
  it("generates a non-root npm Dockerfile with build step and exec-form CMD", () => {
    expect(generateNodeDockerfile(project(), 3000)).toBe(
      [
        "# Generated by Shipyard from package.json.",
        "# To customise the build, commit your own Dockerfile at the repository root.",
        "FROM node:24-slim",
        "WORKDIR /app",
        "RUN chown node:node /app",
        "# Install scripts, the build and the app all run as an unprivileged user.",
        "USER node",
        "COPY --chown=node:node . .",
        "RUN npm ci",
        "RUN npm run build",
        "ENV NODE_ENV=production",
        "ENV PORT=3000",
        "EXPOSE 3000",
        'CMD ["npm","start"]',
        "",
      ].join("\n"),
    );
  });

  it("installs from the manifests first when it can, so the install layer is cached", () => {
    const dockerfile = generateNodeDockerfile(project({ dependencyFiles: ["package.json", "package-lock.json", ".npmrc"] }), 3000, ["API_URL"]);
    expect(dockerfile).toContain(
      [
        "USER node",
        "# Dependencies first, so the install is cached until they change",
        "COPY --chown=node:node package.json package-lock.json .npmrc ./",
        "# Build variables set in Shipyard",
        "ARG API_URL",
        "RUN npm ci",
        "COPY --chown=node:node . .",
        "RUN npm run build",
      ].join("\n"),
    );
  });

  it("refuses a dependency file name that isn't a plain file name", () => {
    expect(() => generateNodeDockerfile(project({ dependencyFiles: ["../etc/passwd"] }), 3000)).toThrow(RangeError);
  });

  it("enables corepack for pnpm and yarn, before switching user", () => {
    const dockerfile = generateNodeDockerfile(project({ packageManager: "pnpm", lockfile: "pnpm-lock.yaml" }), 3000);
    expect(dockerfile).toContain("RUN corepack enable");
    expect(dockerfile.indexOf("corepack enable")).toBeLessThan(dockerfile.indexOf("USER node"));
    expect(dockerfile).toContain('RUN echo "Using pnpm $(pnpm --version)" && pnpm install --frozen-lockfile');
    expect(dockerfile).toContain("RUN pnpm run build");
  });

  it("installs the chosen pnpm/yarn version with corepack, as the build user, before the install", () => {
    const dockerfile = generateNodeDockerfile(
      project({ packageManager: "pnpm", packageManagerMajor: 9, packageManagerVersion: "9.15.0", packageManagerReason: 'packageManager "pnpm@9.15.0" in package.json → pnpm 9.15.0', lockfile: "pnpm-lock.yaml" }),
      3000,
    );
    const lines = dockerfile.split("\n");
    expect(lines).toContain("ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0 COREPACK_ENABLE_AUTO_PIN=0");
    const install = lines.findIndex((line) => line.startsWith('RUN ["sh","-c","for attempt') && line.includes("corepack install --global pnpm@9.15.0 && exit 0"));
    expect(install).toBeGreaterThan(lines.indexOf("USER node"));
    expect(install).toBeLessThan(lines.indexOf('RUN echo "Using pnpm $(pnpm --version)" && pnpm install --frozen-lockfile'));
    expect(lines[install - 1]).toBe('# packageManager "pnpm@9.15.0" in package.json → pnpm 9.15.0');
  });

  it("retries the package-manager download with growing pauses, then says why it gave up", () => {
    const dockerfile = generateNodeDockerfile(project({ packageManager: "pnpm", packageManagerVersion: "9", lockfile: "pnpm-lock.yaml" }), 3000);
    const line = dockerfile.split("\n").find((l) => l.includes("corepack install --global pnpm@9"))!;
    const [, , script] = JSON.parse(line.slice("RUN ".length)) as [string, string, string];
    expect(script).toBe(
      'for attempt in $(seq 1 5); do corepack install --global pnpm@9 && exit 0; [ "$attempt" -eq 5 ] && break; ' +
        'echo "Shipyard: couldn\'t download pnpm@9 (attempt $attempt of 5); retrying in $((attempt * 3))s" >&2; sleep $((attempt * 3)); done; ' +
        'echo "Shipyard: couldn\'t download pnpm@9 from the npm registry after 5 attempts." >&2; exit 1',
    );
  });

  it("yarn Berry: its major from corepack, --immutable", () => {
    const dockerfile = generateNodeDockerfile(project({ packageManager: "yarn", packageManagerMajor: 4, packageManagerVersion: "4", lockfile: "yarn.lock" }), 3000);
    expect(dockerfile).toContain("corepack install --global yarn@4 && exit 0");
    expect(dockerfile).toContain('RUN echo "Using yarn $(yarn --version)" && yarn install --immutable');
  });

  it("bun: the image tagged with the pinned version; npm: a pinned npm replaces the image's", () => {
    expect(generateNodeDockerfile(project({ packageManager: "bun", packageManagerVersion: "1.1.38", lockfile: "bun.lock" }), 3000)).toContain("FROM oven/bun:1.1.38-slim");
    expect(generateNodeDockerfile(project({ packageManager: "bun", lockfile: "bun.lock" }), 3000)).toContain("FROM oven/bun:1-slim");
    const npm = generateNodeDockerfile(project({ packageManagerVersion: "10.9.2" }), 3000);
    expect(npm).toContain("npm install --global npm@10.9.2 && exit 0");
    expect(npm.indexOf("npm@10.9.2")).toBeLessThan(npm.indexOf("USER node"));
    expect(npm).not.toContain("corepack");
  });

  it("refuses a package-manager version that isn't a version, and keeps the reason comment to plain characters", () => {
    expect(() => generateNodeDockerfile(project({ packageManager: "pnpm", packageManagerVersion: "9\nRUN id" }), 3000)).toThrow(RangeError);
    const dockerfile = generateNodeDockerfile(project({ packageManager: "pnpm", packageManagerVersion: "9", packageManagerReason: "lockfileVersion 9.0`$(id)\\\nRUN id" }), 3000);
    expect(dockerfile.split("\n").filter((line) => line.startsWith("RUN id"))).toEqual([]);
    expect(dockerfile).toContain("# lockfileVersion 9.0(id)RUN id");
  });

  it("omits the build step when there is no build script", () => {
    expect(generateNodeDockerfile(project({ hasBuildScript: false }), 3000)).not.toContain("run build");
  });

  it("uses the selected Node version", () => {
    expect(generateNodeDockerfile(project({ nodeMajor: 22 }), 3000)).toContain("FROM node:22-slim\n");
  });

  it("escapes the start command as JSON, so it cannot inject instructions", () => {
    const dockerfile = generateNodeDockerfile(project({ startCommand: ["node", 'a"\nRUN id'] }), 3000);
    expect(dockerfile).toContain('CMD ["node","a\\"\\nRUN id"]');
    expect(dockerfile.split("\n").filter((line) => line.startsWith("RUN id"))).toEqual([]);
  });

  it("declares build variables as ARGs (names only) before install and build", () => {
    const dockerfile = generateNodeDockerfile(project(), 3000, ["API_URL", "SENTRY_RELEASE"]);
    expect(dockerfile).toContain("COPY --chown=node:node . .\n# Build variables set in Shipyard\nARG API_URL\nARG SENTRY_RELEASE\nRUN npm ci");
  });

  it("refuses a build variable name that could inject an instruction", () => {
    expect(() => generateNodeDockerfile(project(), 3000, ["X\nRUN id"])).toThrow(RangeError);
  });

  it.each([0, 70000, 1.5])("rejects port %d", (port) => {
    expect(() => generateNodeDockerfile(project(), port)).toThrow(RangeError);
  });
});

describe("installCommand", () => {
  it.each([
    ["npm", null, "package-lock.json", "npm ci"],
    ["npm", null, null, "npm install"],
    ["pnpm", 9, "pnpm-lock.yaml", "pnpm install --frozen-lockfile"],
    ["pnpm", null, null, "pnpm install"],
    ["bun", 1, "bun.lock", "bun install --frozen-lockfile"],
    ["bun", 1, null, "bun install"],
    ["yarn", null, "yarn.lock", "yarn install --frozen-lockfile"],
    ["yarn", 1, "yarn.lock", "yarn install --frozen-lockfile"],
    ["yarn", 4, "yarn.lock", "yarn install --immutable"],
    ["yarn", 4, null, "yarn install"],
  ] as const)("%s (v%s, lockfile %s) → %s", (packageManager, packageManagerMajor, lockfile, expected) => {
    expect(installCommand({ packageManager, packageManagerMajor, lockfile })).toBe(expected);
  });
});
