import { describe, expect, it } from "vitest";

import { generateNodeDockerfile, installCommand } from "../../src/services/detection/generateDockerfile.js";
import type { NodeProject } from "../../src/services/detection/nodeProject.js";

function project(overrides: Partial<NodeProject> = {}): NodeProject {
  return {
    packageManager: "npm",
    packageManagerMajor: null,
    lockfile: "package-lock.json",
    nodeMajor: 24,
    hasBuildScript: true,
    startCommand: ["npm", "start"],
    notes: [],
    ...overrides,
  };
}

describe("generateNodeDockerfile", () => {
  it("generates a non-root npm Dockerfile with build step and exec-form CMD", () => {
    expect(generateNodeDockerfile(project(), 3000)).toBe(
      [
        "# Generated by Shipyard from package.json.",
        "# To customise the build, commit your own Dockerfile at the repository root.",
        "FROM node:24-slim",
        "WORKDIR /app",
        "RUN chown node:node /app",
        "# Install scripts, the build and the app all run as an unprivileged user.",
        "USER node",
        "COPY --chown=node:node . .",
        "RUN npm ci",
        "RUN npm run build",
        "ENV NODE_ENV=production",
        "ENV PORT=3000",
        "EXPOSE 3000",
        'CMD ["npm","start"]',
        "",
      ].join("\n"),
    );
  });

  it("enables corepack for pnpm and yarn, before switching user", () => {
    const dockerfile = generateNodeDockerfile(project({ packageManager: "pnpm", lockfile: "pnpm-lock.yaml" }), 3000);
    expect(dockerfile).toContain("RUN corepack enable");
    expect(dockerfile.indexOf("corepack enable")).toBeLessThan(dockerfile.indexOf("USER node"));
    expect(dockerfile).toContain("RUN pnpm install --frozen-lockfile");
    expect(dockerfile).toContain("RUN pnpm run build");
  });

  it("omits the build step when there is no build script", () => {
    expect(generateNodeDockerfile(project({ hasBuildScript: false }), 3000)).not.toContain("run build");
  });

  it("uses the selected Node version", () => {
    expect(generateNodeDockerfile(project({ nodeMajor: 22 }), 3000)).toContain("FROM node:22-slim\n");
  });

  it("escapes the start command as JSON, so it cannot inject instructions", () => {
    const dockerfile = generateNodeDockerfile(project({ startCommand: ["node", 'a"\nRUN id'] }), 3000);
    expect(dockerfile).toContain('CMD ["node","a\\"\\nRUN id"]');
    expect(dockerfile.split("\n").filter((line) => line.startsWith("RUN id"))).toEqual([]);
  });

  it("declares build variables as ARGs (names only) before install and build", () => {
    const dockerfile = generateNodeDockerfile(project(), 3000, ["API_URL", "SENTRY_RELEASE"]);
    expect(dockerfile).toContain("COPY --chown=node:node . .\n# Build variables set in Shipyard\nARG API_URL\nARG SENTRY_RELEASE\nRUN npm ci");
  });

  it("refuses a build variable name that could inject an instruction", () => {
    expect(() => generateNodeDockerfile(project(), 3000, ["X\nRUN id"])).toThrow(RangeError);
  });

  it.each([0, 70000, 1.5])("rejects port %d", (port) => {
    expect(() => generateNodeDockerfile(project(), port)).toThrow(RangeError);
  });
});

describe("installCommand", () => {
  it.each([
    ["npm", null, "package-lock.json", "npm ci"],
    ["npm", null, null, "npm install"],
    ["pnpm", 9, "pnpm-lock.yaml", "pnpm install --frozen-lockfile"],
    ["pnpm", null, null, "pnpm install"],
    ["yarn", null, "yarn.lock", "yarn install --frozen-lockfile"],
    ["yarn", 1, "yarn.lock", "yarn install --frozen-lockfile"],
    ["yarn", 4, "yarn.lock", "yarn install --immutable"],
    ["yarn", 4, null, "yarn install"],
  ] as const)("%s (v%s, lockfile %s) → %s", (packageManager, packageManagerMajor, lockfile, expected) => {
    expect(installCommand({ packageManager, packageManagerMajor, lockfile })).toBe(expected);
  });
});
