import { argLines, assertPath, assertPort, dockerignore, runShell, startCommand } from "./dockerfileParts.js";
import { isNestedRegularFile, isRegularFile, listEntries, readNestedFile, readRegularFile } from "./files.js";
import { detectionError } from "./nodeProject.js";
import type { Candidate, DetectContext, Unsupported } from "./types.js";

const MAX_BYTES = 256 * 1024;

/** A port in source code, when the app hard-codes one (the app should read PORT; the generated image sets it). */
function sourcePort(text: string, patterns: readonly RegExp[]): number | null {
  for (const pattern of patterns) {
    const value = Number(pattern.exec(text)?.[1]);
    if (Number.isInteger(value) && value >= 1 && value <= 65535) return value;
  }
  return null;
}

// ───────────── Go ─────────────

/**
 * Go: go.mod. Compiled in a golang image, run from a minimal one (distroless,
 * non-root). The main package is the root (main.go) or the one cmd/<name>.
 */
export async function detectGo(context: DetectContext): Promise<Candidate | null> {
  const gomod = await readRegularFile(context.dir, "go.mod", MAX_BYTES);
  if (gomod === null) return null;
  const reasons = ["go.mod found"];
  const notes: string[] = [];

  const toolchain = /^toolchain\s+go(\d+\.\d+)/m.exec(gomod)?.[1] ?? /^go\s+(\d+\.\d+)/m.exec(gomod)?.[1];
  const image = toolchain && Number(toolchain.split(".")[1]) >= 21 ? `golang:${toolchain}` : "golang:1";
  reasons.push(`go.mod requires Go ${toolchain ?? "(unspecified)"} → ${image}`);

  let pkg: string;
  let mainFile: string;
  if (await isRegularFile(context.dir, "main.go")) {
    pkg = ".";
    mainFile = "main.go";
  } else {
    const commands = (await listEntries(`${context.dir}/cmd`, 200)).filter((entry) => entry.kind === "directory").map((entry) => entry.name);
    const withMain: string[] = [];
    for (const name of commands) if (await isNestedRegularFile(context.dir, `cmd/${name}/main.go`)) withMain.push(name);
    const module = /^module\s+(\S+)/m.exec(gomod)?.[1]?.split("/").pop();
    const preferred = withMain.length === 1 ? withMain[0] : withMain.find((name) => name === module) ?? withMain.find((name) => ["server", "api", "web", "app"].includes(name));
    if (!preferred) {
      if (withMain.length === 0) {
        throw detectionError("This Go module has no main package Shipyard can find (main.go at its root, or cmd/<name>/main.go). Set a start command or add a Dockerfile.");
      }
      throw detectionError(`This Go module has several commands (${withMain.map((name) => `cmd/${name}`).join(", ")}); Shipyard can't tell which one is the service. Add a Dockerfile, or a main.go at the root.`);
    }
    pkg = `./cmd/${preferred}`;
    mainFile = `cmd/${preferred}/main.go`;
    if (withMain.length > 1) reasons.push(`several commands; chose cmd/${preferred} (${preferred === module ? "named like the module" : "a server name"})`);
  }
  assertPath(mainFile);
  reasons.push(`main package: ${pkg === "." ? "the root (main.go)" : pkg}`);

  const main = (await readNestedFile(context.dir, mainFile, MAX_BYTES).catch(() => null)) ?? "";
  const readsPort = /Getenv\(\s*"PORT"\s*\)/.test(main);
  const hardcoded = readsPort ? null : sourcePort(main, [/ListenAndServe(?:TLS)?\(\s*"[^"]*:(\d+)"/, /\.(?:Run|Start|Listen)\(\s*"[^"]*:(\d+)"/, /Addr:\s*"[^"]*:(\d+)"/]);
  const cgo = /github\.com\/mattn\/go-sqlite3/.test(gomod);
  if (cgo) notes.push("go-sqlite3 needs cgo: built with CGO_ENABLED=1 and run on Debian slim.");
  const web = /net\/http|gin-gonic|labstack\/echo|gofiber|go-chi|gorilla\/mux/.test(gomod + main);

  return {
    projectType: "go",
    language: "Go",
    runtime: image.replace("golang:", "Go "),
    framework: frameworkFrom(gomod, [["gin-gonic/gin", "Gin"], ["labstack/echo", "Echo"], ["gofiber/fiber", "Fiber"], ["go-chi/chi", "chi"], ["gorilla/mux", "Gorilla"]]),
    packageManager: "go",
    entrypoint: pkg,
    buildCommand: `go build -o /out/app ${pkg}`,
    startCommand: context.overrides.startCommand ?? "/app",
    port: hardcoded ?? 8080,
    portSource: hardcoded ? `hard-coded in ${mainFile}` : readsPort ? "Go default (the app reads PORT)" : "Go default",
    confidence: web ? 0.9 : 0.8,
    reasons,
    notes,
    contextDirectory: context.rel,
    app: true,
    dockerfile: {
      kind: "generated",
      dockerignore: dockerignore(),
      render: (input) => {
        const port = assertPort(input.port);
        // A configured start command needs a shell, which distroless doesn't have.
        const runtime = cgo || input.startCommand ? "debian:bookworm-slim" : "gcr.io/distroless/static-debian12:nonroot";
        const lines = [
          "# Generated by Shipyard from go.mod. To customise it, commit your own Dockerfile.",
          `FROM ${image} AS build`,
          "WORKDIR /src",
          "COPY go.mod go.sum* ./",
          "RUN go mod download",
          "COPY . .",
          ...argLines(input.buildArgNames),
          input.buildCommand ? runShell(input.buildCommand) : `RUN CGO_ENABLED=${cgo ? 1 : 0} go build -trimpath -ldflags="-s -w" -o /out/app ${pkg}`,
          `FROM ${runtime}`,
        ];
        if (runtime.startsWith("debian")) lines.push("RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/* && useradd --uid 10001 app", "USER app");
        lines.push("COPY --from=build /out/app /app", `ENV PORT=${port}`, `EXPOSE ${port}`, startCommand(input.startCommand, ["/app"]));
        return `${lines.join("\n")}\n`;
      },
    },
  };
}

// ───────────── Java ─────────────

/** Eclipse Temurin releases with -jdk and -jre images. */
const JAVA_VERSIONS = [8, 11, 17, 21, 25] as const;

/**
 * Java: Maven (pom.xml) or Gradle (build.gradle[.kts]), via the project's
 * wrapper when it has one. Builds the jar in a JDK image and runs it on a JRE.
 * Spring Boot gets its executable jar (bootJar); Quarkus its fast-jar.
 */
export async function detectJava(context: DetectContext): Promise<Candidate | null> {
  const pom = await readRegularFile(context.dir, "pom.xml", MAX_BYTES);
  const gradle = (await readRegularFile(context.dir, "build.gradle", MAX_BYTES)) ?? (await readRegularFile(context.dir, "build.gradle.kts", MAX_BYTES));
  if (pom === null && gradle === null) return null;
  const build = pom ?? gradle ?? "";
  const tool = pom !== null ? "maven" : "gradle";
  const reasons = [`${pom !== null ? "pom.xml" : "build.gradle"} found → ${tool === "maven" ? "Maven" : "Gradle"}`];
  const notes: string[] = [];

  const spring = /spring-boot/.test(build);
  const quarkus = /io\.quarkus/.test(build);
  const framework = spring ? "Spring Boot" : quarkus ? "Quarkus" : /micronaut/.test(build) ? "Micronaut" : null;
  if (framework) reasons.push(`${framework} in the build file`);
  else notes.push("No Spring Boot, Quarkus or Micronaut found: the build must produce an executable jar (Main-Class in its manifest).");

  const requested = Number(
    /<java\.version>\s*(\d+)/.exec(build)?.[1] ??
      /<maven\.compiler\.(?:release|source|target)>\s*(?:1\.)?(\d+)/.exec(build)?.[1] ??
      /<release>\s*(\d+)/.exec(build)?.[1] ??
      /JavaLanguageVersion\.of\(\s*(\d+)\s*\)/.exec(build)?.[1] ??
      /JavaVersion\.VERSION_(?:1_)?(\d+)/.exec(build)?.[1] ??
      /sourceCompatibility\s*=\s*['"]?(?:1\.)?(\d+)/.exec(build)?.[1] ??
      21,
  );
  const java = JAVA_VERSIONS.find((version) => version >= requested) ?? 25;
  reasons.push(`Java ${requested} → Temurin ${java}`);

  const wrapper = tool === "maven" ? await isRegularFile(context.dir, "mvnw") : await isRegularFile(context.dir, "gradlew");
  const task = tool === "gradle" ? (spring ? "bootJar" : quarkus ? "quarkusBuild" : "build") : "package";
  const buildCommand =
    tool === "maven"
      ? `${wrapper ? "sh mvnw" : "mvn"} -B -DskipTests package`
      : `${wrapper ? "sh gradlew" : "gradle"} --no-daemon ${task} -x test`;
  const buildImage = wrapper ? `eclipse-temurin:${java}-jdk` : tool === "maven" ? `maven:3.9-eclipse-temurin-${java}` : `gradle:8-jdk${java}`;
  const output = tool === "maven" ? "target" : "build";

  const properties = (await readNestedFile(context.dir, "src/main/resources/application.properties", MAX_BYTES).catch(() => null)) ?? "";
  const yaml = (await readNestedFile(context.dir, "src/main/resources/application.yml", MAX_BYTES).catch(() => null)) ?? "";
  const configured = sourcePort(properties, [/^server\.port\s*=\s*(\d+)/m]) ?? sourcePort(yaml, [/^server:\s*\n(?:\s+.*\n)*?\s+port:\s*(\d+)/m]);
  if (configured) reasons.push(`server.port=${configured} in application config`);

  return {
    projectType: "java",
    language: "Java",
    runtime: `Java ${java}`,
    framework,
    packageManager: tool,
    entrypoint: quarkus ? `${output}/quarkus-app/quarkus-run.jar` : `${output}/…/*.jar`,
    buildCommand,
    startCommand: context.overrides.startCommand ?? "java -jar app.jar",
    port: configured ?? 8080,
    portSource: configured ? "server.port in application config" : `${framework ?? "Java"} default`,
    confidence: framework ? 0.9 : 0.7,
    reasons,
    notes,
    contextDirectory: context.rel,
    app: true,
    dockerfile: {
      kind: "generated",
      dockerignore: dockerignore("target", "build", ".gradle"),
      render: (input) => {
        const port = assertPort(input.port);
        const jarDir = tool === "maven" ? "target" : "build/libs";
        const collect = quarkus
          ? `cp -R ${output}/quarkus-app /out && mv /out/quarkus-run.jar /out/app.jar`
          : `jar=$(find ${jarDir} -maxdepth 1 -name '*.jar' ! -name '*-plain.jar' ! -name 'original-*' ! -name '*-sources.jar' ! -name '*-javadoc.jar' | head -n 1); test -n "$jar" || { echo "The build produced no runnable jar in ${jarDir}/" >&2; exit 1; }; mkdir -p /out && cp "$jar" /out/app.jar`;
        const lines = [
          `# Generated by Shipyard for a ${framework ?? "Java"} app. To customise it, commit your own Dockerfile.`,
          `FROM ${buildImage} AS build`,
          "WORKDIR /src",
          "COPY . .",
          ...argLines(input.buildArgNames),
          input.buildCommand ? runShell(input.buildCommand) : `RUN ${buildCommand}`,
          `RUN ${JSON.stringify(["sh", "-c", collect])}`,
          `FROM eclipse-temurin:${java}-jre`,
          "RUN useradd --system --uid 10001 app",
          "WORKDIR /app",
          "COPY --from=build /out/ /app/",
          "USER app",
          // Spring Boot reads SERVER_PORT, Quarkus QUARKUS_HTTP_PORT, Micronaut MICRONAUT_SERVER_PORT.
          `ENV PORT=${port} SERVER_PORT=${port} QUARKUS_HTTP_PORT=${port} QUARKUS_HTTP_HOST=0.0.0.0 MICRONAUT_SERVER_PORT=${port}`,
          `EXPOSE ${port}`,
          startCommand(input.startCommand, ["sh", "-c", "exec java $JAVA_OPTS -jar /app/app.jar"]),
        ];
        return `${lines.join("\n")}\n`;
      },
    },
  };
}

// ───────────── Rust ─────────────

const CRATE_NAME = /^[A-Za-z0-9_-]{1,64}$/;

/** Rust: Cargo.toml. Built with cargo in a rust image, the binary run on Debian slim as a non-root user. */
export async function detectRust(context: DetectContext): Promise<Candidate | Unsupported | null> {
  const cargo = await readRegularFile(context.dir, "Cargo.toml", MAX_BYTES);
  if (cargo === null) return null;
  const reasons = ["Cargo.toml found"];
  const notes: string[] = [];

  const packageSection = /^\[package\]([\s\S]*?)(?=^\[|$(?![\s\S]))/m.exec(cargo)?.[1] ?? "";
  const packageName = /^\s*name\s*=\s*"([^"]+)"/m.exec(packageSection)?.[1];
  if (!packageName && /^\[workspace\]/m.test(cargo)) {
    const members = /members\s*=\s*\[([^\]]*)\]/.exec(cargo)?.[1]?.match(/"([^"]+)"/g)?.map((m) => m.slice(1, -1)) ?? [];
    throw detectionError(
      `This is a Cargo workspace${members.length ? ` (${members.join(", ")})` : ""}; Shipyard can't tell which crate is the service. Add a Dockerfile that builds the right one.`,
    );
  }
  const bins = [...cargo.matchAll(/^\[\[bin\]\]([\s\S]*?)(?=^\[|$(?![\s\S]))/gm)].map((m) => /^\s*name\s*=\s*"([^"]+)"/m.exec(m[1] ?? "")?.[1]).filter((n): n is string => Boolean(n));
  let binary: string | undefined;
  if (bins.length > 0) {
    binary = bins.length === 1 ? bins[0] : bins.find((name) => name === packageName);
    if (!binary) throw detectionError(`Cargo.toml declares several binaries (${bins.join(", ")}) and none is named like the package; add a Dockerfile that runs the right one.`);
  } else if (await isNestedRegularFile(context.dir, "src/main.rs")) {
    binary = packageName;
  } else {
    return { unsupported: `${context.rel === "." ? "The repository" : context.rel} is a Rust library (no src/main.rs or [[bin]]): there's nothing to run.` };
  }
  if (!binary || !CRATE_NAME.test(binary)) throw detectionError("Cargo.toml's package name isn't a plain crate name; add a Dockerfile.");
  reasons.push(`binary: ${binary}`);

  const framework = frameworkFrom(cargo, [["actix-web", "Actix Web"], ["axum", "Axum"], ["rocket", "Rocket"], ["warp", "warp"], ["poem", "Poem"], ["tide", "Tide"]]);
  if (framework) reasons.push(`${framework} in dependencies`);
  else notes.push("No web framework in Cargo.toml: it runs as a process; health checks need it to answer HTTP if it is a web service.");
  const main = (await readNestedFile(context.dir, "src/main.rs", MAX_BYTES).catch(() => null)) ?? "";
  const readsPort = /env::var\(\s*"PORT"\s*\)/.test(main);
  const hardcoded = readsPort ? null : sourcePort(main, [/"0\.0\.0\.0:(\d+)"/, /\(\s*"0\.0\.0\.0"\s*,\s*(\d+)\s*\)/, /\[0,\s*0,\s*0,\s*0\],\s*(\d+)/]);
  if (/"127\.0\.0\.1:\d+"|"localhost:\d+"/.test(main)) notes.push("src/main.rs binds to 127.0.0.1/localhost: bind 0.0.0.0, or it can't be reached from outside the container.");
  const port = hardcoded ?? (framework === "Rocket" ? 8000 : 8080);
  const toolchain = /^\s*channel\s*=\s*"(\d+\.\d+)(?:\.\d+)?"/m.exec((await readRegularFile(context.dir, "rust-toolchain.toml", 4096)) ?? "")?.[1];
  const locked = await isRegularFile(context.dir, "Cargo.lock");

  return {
    projectType: "rust",
    language: "Rust",
    runtime: `Rust ${toolchain ?? "stable"}`,
    framework,
    packageManager: "cargo",
    entrypoint: binary,
    buildCommand: `cargo build --release${locked ? " --locked" : ""} --bin ${binary}`,
    startCommand: context.overrides.startCommand ?? `/usr/local/bin/${binary}`,
    port,
    portSource: hardcoded ? "hard-coded in src/main.rs" : `${framework ?? "Rust"} default${readsPort ? " (the app reads PORT)" : ""}`,
    confidence: framework ? 0.9 : 0.65,
    reasons,
    notes,
    contextDirectory: context.rel,
    app: true,
    dockerfile: {
      kind: "generated",
      dockerignore: dockerignore("target"),
      render: (input) => {
        const p = assertPort(input.port);
        const lines = [
          "# Generated by Shipyard from Cargo.toml. To customise it, commit your own Dockerfile.",
          `FROM rust:${toolchain ?? "1"}-slim-bookworm AS build`,
          "RUN apt-get update && apt-get install -y --no-install-recommends pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*",
          "WORKDIR /src",
          "COPY . .",
          ...argLines(input.buildArgNames),
          input.buildCommand ? runShell(input.buildCommand) : `RUN cargo build --release${locked ? " --locked" : ""} --bin ${binary}`,
          "FROM debian:bookworm-slim",
          "RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates libssl3 && rm -rf /var/lib/apt/lists/* && useradd --uid 10001 app",
          `COPY --from=build /src/target/release/${binary} /usr/local/bin/${binary}`,
          "USER app",
          `ENV PORT=${p} ROCKET_ADDRESS=0.0.0.0 ROCKET_PORT=${p}`,
          `EXPOSE ${p}`,
          startCommand(input.startCommand, [`/usr/local/bin/${binary}`]),
        ];
        return `${lines.join("\n")}\n`;
      },
    },
  };
}

function frameworkFrom(text: string, known: ReadonlyArray<[needle: string, name: string]>): string | null {
  return known.find(([needle]) => text.includes(needle))?.[1] ?? null;
}
