import { isSafeRelativePath } from "./files.js";

/**
 * Building blocks for generated Dockerfiles. Every RUN line is a fixed
 * template; values that come from a repository (paths, module names,
 * commands) are validated first, and commands are emitted in exec (JSON)
 * form so they reach `sh -c` as one argument instead of being spliced into
 * Dockerfile syntax.
 */

export const NGINX_IMAGE = "nginxinc/nginx-unprivileged:1.27-alpine";

export function assertPort(port: number): number {
  if (!Number.isInteger(port) || port < 1 || port > 65535) throw new RangeError(`Invalid port: ${port}`);
  return port;
}

/** Build variable names come from the user: allow exactly what the API allows, nothing that could break a line. */
export function assertArgName(name: string): string {
  if (!/^[A-Za-z_][A-Za-z0-9_]{0,127}$/.test(name)) throw new RangeError(`Invalid build variable name: ${name}`);
  return name;
}

/** A repository path written into a Dockerfile. */
export function assertPath(value: string): string {
  if (!isSafeRelativePath(value)) throw new RangeError(`Unsafe path: ${value}`);
  return value;
}

export function argLines(names: readonly string[]): string[] {
  if (names.length === 0) return [];
  // Names only: values are passed to `docker build`, never written into this file.
  return ["# Build variables set in Shipyard", ...names.map(assertArgName).map((name) => `ARG ${name}`)];
}

/** `RUN ["sh","-c","<command>"]`: a configured command, one argument, no Dockerfile parsing of its content. */
export function runShell(command: string): string {
  return `RUN ${JSON.stringify(["sh", "-c", command])}`;
}

export function cmd(command: readonly string[]): string {
  return `CMD ${JSON.stringify(command)}`;
}

/** The start command: a configured one through a shell, else the detected exec-form one. */
export function startCommand(configured: string | null, detected: readonly string[]): string {
  return cmd(configured ? ["sh", "-c", configured] : detected);
}

/**
 * nginx serving /usr/share/nginx/html on `port`. Dotfiles (.env, .git) are
 * never served. `spa`: unknown paths get index.html (client-side routing).
 */
export function nginxConfigLines(port: number, spa: boolean): string[] {
  const config = [
    "server {",
    `  listen ${assertPort(port)};`,
    "  server_name _;",
    "  root /usr/share/nginx/html;",
    "  index index.html;",
    "  location ~ /\\. { return 404; }",
    spa ? "  location / { try_files $uri $uri/ /index.html; }" : "  location / { try_files $uri $uri/ =404; }",
    "}",
  ];
  return [
    "USER root",
    `RUN printf '%s\\n' ${config.map((line) => `'${line}'`).join(" ")} > /etc/nginx/conf.d/default.conf`,
    "USER 101",
  ];
}

/** Ignore rules written only when the repository has no .dockerignore of its own. */
export function dockerignore(...entries: string[]): string {
  return ["# Generated by Shipyard.", ".git", ...entries, ""].join("\n");
}
