import type { NodeProject, PackageManager } from "./nodeProject.js";

/**
 * Turns a detected Node project into a Dockerfile. Pure: same input, same text.
 *
 * Every RUN line comes from a fixed template below, never from repository
 * content. The only repository-derived value, the start command, is validated
 * by detection and emitted in exec (JSON) form, so it never passes through a shell.
 */
export function generateNodeDockerfile(project: NodeProject, port: number, buildArgNames: readonly string[] = []): string {
  if (!Number.isInteger(port) || port < 1 || port > 65535) throw new RangeError(`Invalid port: ${port}`);

  const pm = project.packageManager;
  const lines = [
    "# Generated by Shipyard from package.json.",
    "# To customise the build, commit your own Dockerfile at the repository root.",
    // -slim (Debian) rather than -alpine: native modules built for glibc just work.
    `FROM node:${project.nodeMajor}-slim`,
  ];

  if (pm !== "npm") {
    // Corepack provides pnpm/yarn at the version pinned in package.json "packageManager".
    lines.push("ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0", "RUN corepack enable");
  }

  lines.push(
    "WORKDIR /app",
    "RUN chown node:node /app",
    "# Install scripts, the build and the app all run as an unprivileged user.",
    "USER node",
  );
  if (project.dependencyFiles) {
    // Manifests first: Docker reuses the install layer until one of them changes.
    lines.push(
      "# Dependencies first, so the install is cached until they change",
      `COPY --chown=node:node ${project.dependencyFiles.map(assertFileName).join(" ")} ./`,
    );
  } else {
    // Whole source before install: install scripts and workspaces may need it.
    lines.push("COPY --chown=node:node . .");
  }
  if (buildArgNames.length > 0) {
    // Names only: values are passed to `docker build`, never written into this file.
    lines.push("# Build variables set in Shipyard", ...buildArgNames.map(assertArgName).map((name) => `ARG ${name}`));
  }
  lines.push(`RUN ${installCommand(project)}`);
  if (project.dependencyFiles) lines.push("COPY --chown=node:node . .");

  if (project.hasBuildScript) lines.push(`RUN ${pm} run build`);

  lines.push(
    "ENV NODE_ENV=production",
    `ENV PORT=${port}`,
    `EXPOSE ${port}`,
    `CMD ${JSON.stringify(project.startCommand)}`,
  );

  return `${lines.join("\n")}\n`;
}

/** Dependency files come from a fixed list (package.json, lockfiles, rc files); refuse anything else. */
function assertFileName(name: string): string {
  if (!/^\.?[A-Za-z0-9][A-Za-z0-9._-]*$/.test(name)) throw new RangeError(`Invalid dependency file name: ${name}`);
  return name;
}

/** Build variable names come from the user: allow exactly what the API allows, nothing that could break a line. */
function assertArgName(name: string): string {
  if (!/^[A-Za-z_][A-Za-z0-9_]{0,127}$/.test(name)) throw new RangeError(`Invalid build variable name: ${name}`);
  return name;
}

/** Ignore rules written only when the repository has no .dockerignore of its own. */
export const GENERATED_DOCKERIGNORE = [
  "# Generated by Shipyard.",
  // Host node_modules may hold binaries for the wrong OS/CPU; always install fresh.
  "node_modules",
  ".git",
  "npm-debug.log*",
  "",
].join("\n");

/** Dev dependencies are installed too: most build scripts need them. */
export function installCommand(project: Pick<NodeProject, "packageManager" | "packageManagerMajor" | "lockfile">): string {
  const locked = project.lockfile !== null;
  const commands: Record<PackageManager, string> = {
    npm: locked ? "npm ci" : "npm install",
    pnpm: locked ? "pnpm install --frozen-lockfile" : "pnpm install",
    yarn: !locked
      ? "yarn install"
      : (project.packageManagerMajor ?? 1) >= 2
        ? "yarn install --immutable"
        : "yarn install --frozen-lockfile",
  };
  return commands[project.packageManager];
}
