import type { NodeProject, PackageManager } from "./nodeProject.js";

/**
 * Turns a detected Node project into a Dockerfile. Pure: same input, same text.
 *
 * Every RUN line comes from a fixed template below, never from repository
 * content. The only repository-derived value, the start command, is validated
 * by detection and emitted in exec (JSON) form, so it never passes through a shell.
 */
export function generateNodeDockerfile(project: NodeProject, port: number): string {
  if (!Number.isInteger(port) || port < 1 || port > 65535) throw new RangeError(`Invalid port: ${port}`);

  const pm = project.packageManager;
  const lines = [
    "# Generated by Shipyard from package.json.",
    "# To customise the build, commit your own Dockerfile at the repository root.",
    // -slim (Debian) rather than -alpine: native modules built for glibc just work.
    `FROM node:${project.nodeMajor}-slim`,
  ];

  if (pm !== "npm") {
    // Corepack provides pnpm/yarn at the version pinned in package.json "packageManager".
    lines.push("ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0", "RUN corepack enable");
  }

  lines.push(
    "WORKDIR /app",
    "RUN chown node:node /app",
    "# Install scripts, the build and the app all run as an unprivileged user.",
    "USER node",
    // Whole source before install: correct for postinstall scripts and workspaces,
    // at the cost of re-installing on every change (build caching comes later).
    "COPY --chown=node:node . .",
    `RUN ${installCommand(project)}`,
  );

  if (project.hasBuildScript) lines.push(`RUN ${pm} run build`);

  lines.push(
    "ENV NODE_ENV=production",
    `ENV PORT=${port}`,
    `EXPOSE ${port}`,
    `CMD ${JSON.stringify(project.startCommand)}`,
  );

  return `${lines.join("\n")}\n`;
}

/** Ignore rules written only when the repository has no .dockerignore of its own. */
export const GENERATED_DOCKERIGNORE = [
  "# Generated by Shipyard.",
  // Host node_modules may hold binaries for the wrong OS/CPU; always install fresh.
  "node_modules",
  ".git",
  "npm-debug.log*",
  "",
].join("\n");

/** Dev dependencies are installed too: most build scripts need them. */
export function installCommand(project: Pick<NodeProject, "packageManager" | "packageManagerMajor" | "lockfile">): string {
  const locked = project.lockfile !== null;
  const commands: Record<PackageManager, string> = {
    npm: locked ? "npm ci" : "npm install",
    pnpm: locked ? "pnpm install --frozen-lockfile" : "pnpm install",
    yarn: !locked
      ? "yarn install"
      : (project.packageManagerMajor ?? 1) >= 2
        ? "yarn install --immutable"
        : "yarn install --frozen-lockfile",
  };
  return commands[project.packageManager];
}
