import semver from "semver";

import { argLines, assertPort, dockerignore, runShell, startCommand } from "./dockerfileParts.js";
import { isNestedRegularFile, isRegularFile, readRegularFile } from "./files.js";
import type { Candidate, DetectContext } from "./types.js";

/** Official php:<version>-apache images, newest first. */
export const PHP_VERSIONS = ["8.4", "8.3", "8.2", "8.1"] as const;
export const DEFAULT_PHP = "8.3";

/**
 * PHP: composer.json, index.php or public/index.php. Laravel and Symfony
 * (and anything with public/index.php) are served from public/; plain PHP
 * from the directory itself. Apache with mod_php, the common setup.
 */
export async function detectPhp(context: DetectContext): Promise<Candidate | null> {
  const { dir } = context;
  const composerRaw = await readRegularFile(dir, "composer.json", 512 * 1024);
  const publicIndex = await isNestedRegularFile(dir, "public/index.php");
  const rootIndex = await isRegularFile(dir, "index.php");
  if (composerRaw === null && !publicIndex && !rootIndex) return null;

  const reasons: string[] = [];
  const notes: string[] = [];
  let composer: { require?: Record<string, string> } = {};
  if (composerRaw !== null) {
    try {
      composer = JSON.parse(composerRaw) as typeof composer;
    } catch {
      notes.push("composer.json is not valid JSON; dependencies may not install.");
    }
    reasons.push("composer.json found");
  }
  const requires = composer.require ?? {};
  const laravel = "laravel/framework" in requires || (await isRegularFile(dir, "artisan"));
  const symfony = "symfony/framework-bundle" in requires;
  const framework = laravel ? "Laravel" : symfony ? "Symfony" : null;
  const docroot = laravel || symfony || publicIndex ? "public" : ".";
  if (framework) reasons.push(`${laravel ? "laravel/framework / artisan" : "symfony/framework-bundle"} → ${framework}`);
  reasons.push(docroot === "public" ? "served from public/" : "served from the directory itself (index.php)");
  if (!framework && !publicIndex && !rootIndex) {
    // A Composer package with no entry point is a library.
    return null;
  }
  if (laravel) notes.push("Laravel needs APP_KEY (php artisan key:generate --show) and its database settings as variables.");

  const version = phpVersion(requires.php, notes);
  const hasComposer = composerRaw !== null;
  return {
    projectType: "php",
    language: "PHP",
    runtime: `PHP ${version}`,
    framework,
    packageManager: hasComposer ? "composer" : null,
    entrypoint: docroot === "public" ? "public/index.php" : "index.php",
    buildCommand: hasComposer ? "composer install --no-dev --optimize-autoloader" : null,
    startCommand: context.overrides.startCommand ?? "apache2-foreground",
    port: 8080,
    portSource: "Apache in the generated image",
    confidence: framework ? 0.95 : 0.85,
    reasons,
    notes,
    contextDirectory: context.rel,
    app: true,
    dockerfile: {
      kind: "generated",
      dockerignore: dockerignore("vendor", "node_modules"),
      render: (input) => {
        const port = assertPort(input.port);
        const lines = [
          `# Generated by Shipyard for a ${framework ?? "PHP"} app. To customise it, commit your own Dockerfile.`,
          `FROM php:${version}-apache`,
        ];
        if (hasComposer) {
          lines.push(
            "RUN apt-get update && apt-get install -y --no-install-recommends git unzip libzip-dev libpq-dev && docker-php-ext-install pdo_mysql pdo_pgsql zip && rm -rf /var/lib/apt/lists/*",
            "COPY --from=composer:2 /usr/bin/composer /usr/bin/composer",
          );
        }
        lines.push(
          "RUN a2enmod rewrite",
          `RUN sed -i 's/^Listen 80$/Listen ${port}/' /etc/apache2/ports.conf && sed -i 's/<VirtualHost \\*:80>/<VirtualHost *:${port}>/' /etc/apache2/sites-available/000-default.conf`,
        );
        if (docroot === "public") {
          lines.push(
            "ENV APACHE_DOCUMENT_ROOT=/var/www/html/public",
            "RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf",
          );
        }
        lines.push(
          // .htaccess routing (Laravel, Symfony) needs AllowOverride.
          "RUN printf '%s\\n' '<Directory /var/www/html>' '  AllowOverride All' '</Directory>' > /etc/apache2/conf-available/shipyard.conf && a2enconf shipyard",
          "WORKDIR /var/www/html",
          ...argLines(input.buildArgNames),
          "COPY . .",
        );
        if (hasComposer) lines.push("ENV COMPOSER_ALLOW_SUPERUSER=1", "RUN composer install --no-dev --optimize-autoloader --no-interaction --no-progress");
        if (input.buildCommand) lines.push(runShell(input.buildCommand));
        lines.push(
          // Apache's workers run as www-data; Laravel writes to storage/ and bootstrap/cache.
          "RUN chown -R www-data:www-data /var/www/html",
          `ENV PORT=${port}`,
          `EXPOSE ${port}`,
          startCommand(input.startCommand, ["apache2-foreground"]),
        );
        return `${lines.join("\n")}\n`;
      },
    },
  };
}

function phpVersion(constraint: string | undefined, notes: string[]): string {
  if (!constraint) return DEFAULT_PHP;
  const range = constraint.replace(/\|\|?/g, " || ").replace(/,/g, " ");
  if (!semver.validRange(range)) return DEFAULT_PHP;
  const ordered = [DEFAULT_PHP, ...PHP_VERSIONS.filter((v) => v !== DEFAULT_PHP)];
  const match = ordered.find((v) => semver.intersects(range, `~${v}.0`));
  if (match) return match;
  notes.push(`composer.json requires PHP "${constraint}", which no generated image provides; using ${DEFAULT_PHP}.`);
  return DEFAULT_PHP;
}
